version: '3.8'

services:
  accountability-buddy:
    image: python:3.9-slim
    container_name: accountability-buddy
    restart: unless-stopped

    environment:
      # GitHub Configuration
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - GITHUB_REPO=${GITHUB_REPO:-pdmthorsrud/accountability_buddy}

      # Required: Vapi API Configuration
      - VAPI_API_TOKEN=${VAPI_API_TOKEN}

      # Required: Assistant IDs
      - MORNING_ASSISTANT_ID=${MORNING_ASSISTANT_ID}
      - EVENING_ASSISTANT_ID=${EVENING_ASSISTANT_ID}

      # Required: Phone Configuration
      - PHONE_NUMBER_ID=${PHONE_NUMBER_ID}
      - TARGET_PHONE_NUMBER=${TARGET_PHONE_NUMBER}

      # Optional: Customize call times (cron format)
      # Default: Morning at 8:00 AM, Evening at 8:00 PM
      - MORNING_CALL_TIME=${MORNING_CALL_TIME:-0 8 * * *}
      - EVENING_CALL_TIME=${EVENING_CALL_TIME:-0 20 * * *}

      # Timezone
      - TZ=${TZ:-Europe/Oslo}

    volumes:
      # Optional: Mount logs directory to access logs from host
      - ./logs:/app/logs

    command: >
      bash -c "
        set -e
        apt-get update && apt-get install -y --no-install-recommends git cron &&
        cd /app &&
        git clone https://$$GITHUB_TOKEN@github.com/$$GITHUB_REPO.git &&
        cd $(basename \"$${GITHUB_REPO}\") &&
        ./setup_production.sh
      "

    working_dir: /app
